import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Grid from "@/components/Grid";
import Card from "@/components/Card";
import Chart from "@/components/Chart";

const data = [
  {
    Year: 2018,
    Amount: 20,
    Group: "A",
    Description: "Running on-demand all A instances",
  },
  {
    Year: 2019,
    Amount: 40,
    Group: "B",
    Description: "Running on-demand all B instances",
  },
  {
    Year: 2020,
    Amount: 39,
    Group: "C",
    Description: "Running on-demand all C instances",
  },
  {
    Year: 2021,
    Amount: 10,
    Group: "D",
    Description: "Running on-demand all D instances",
  },
  {
    Year: 2022,
    Amount: 55,
    Group: "E",
    Description: "Running on-demand all E instances",
  },
  {
    Year: 2023,
    Amount: 70,
    Group: "F",
    Description: "Running on-demand all F instances",
  },
];

const gridData = {
  columns: ["Year", "Amount", "Group", "Description"],
  rows: data,
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Syndica Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>Syndica Assessment</div>
        <Card header="Flexible Grid">
          <Grid data={gridData} />
        </Card>
        <Card header="Chart">
          <Chart data={data} />
        </Card>
      </main>
    </>
  );
}
